### PR TITLE
Handle no available audio device in a recoverable manner.

### PR DESCRIPTION
**Pull request by richardeakin**
Previously the MSW Media Foundation implementation would blow up on an assertion failure if you tried to make a default audio input or output device and there wasn't connected hardware for that. Now the solution is as follows:

* `Device::getDefault[Input|Output]()` will return nullptr (empty `DeviceRef`) if there is no input or output device.
* Calling `Context::create[Input|Output]DeviceNode()` will cause an exception to be thrown if there is no default input or output device. This can be avoided by first querying for the default input or output device node before doing any other audio graph configuration.

### CODE REVIEW

**Comment by brucelane** [comment]
that is going to be useful for me, thank you!

**Comment by brucelane** [comment]
hi,
would it be possible to remove the exception when the audio in is not present : https://github.com/cinder/Cinder/blob/master/src/cinder/audio/InputNode.cpp#L66
it causes my app to quit
thank you

**Comment by richardeakin** [comment]
@brucelane apologies, I only now saw this. Can you explain a little what you mean by 'audio is not present'?

I would think that if the platform doesn't have a microphone and you try to create an `audio:: InputDeviceNode`, then an exception should be thrown to indicate that it isn't possible. To me this is better than returning a null object as it forces you to deal with the situation and provides better diagnostics.

**Comment by brucelane** [comment]
when there no mic in (or it is disabled)...
it does reach the catch exception handled within a try/catch block, so there is always a crash...

**Comment by richardeakin** [comment]
Do you mean that you are loading the `InputDeviceNode` from within a try / catch block, or you aren't and so you crash because of an uncaught exception?

If you don't want to use a try / catch, you can also check if there is a input device available first:
```cpp
if( audio::Device::getDefaultInput() ) {
     ...
}
```

**Comment by brucelane** [comment]
yes, from within a try / catch block, but I removed it as it was useless
My code is here : https://github.com/videodromm/Cinder-Videodromm/blob/master/src/VDTexture.cpp#L919
getDefaultInput() will definitely be helpful, thank you

**Pull request merged**
