### PR TITLE
Deferred shading sample updates

### PR DESCRIPTION
**Pull request by BanTheRewind**

### CODE REVIEW

**Comment by BanTheRewind** [comment]
Went through this with a fine-toothed comb. Should be good to go now.

**Comment by BanTheRewind** [comment]
Went through this with a fine-toothed comb. Should be good to go now.

**Comment by BanTheRewind** [comment]
Sorry, just had to sneak in volumetric light rays before the merge.  ;)

**Comment by richardeakin** [comment]
My guess is that this won't auto merge because of my change in #876, where the name for ScopedAlphaBlend changed to ScopedBlendAlpha. You might want to resolve that on your end so that it is how you like, otherwise I can do it once the updates are finished.

**Comment by BanTheRewind** [comment]
Will do tonight and let you know.

**Comment by BanTheRewind** [comment]
Merged from cinder:glNext and updated samples with new scoped blends. Good to go.

**Comment by BanTheRewind** [comment]
Closing this PR so I can make a cleaner one. I'm going to fork the current glNext, add my samples to it, and then PR again. One sec...

**Comment by BanTheRewind** [comment]
Unable to test due against latest due to #890 . :/

**Pull request closed without merging**
