### PR TITLE
ScopedVao const correctness.

### PR DESCRIPTION
**Pull request by sansumbrella**
Receive a `const VaoRef &` in constructor.

### CODE REVIEW

**Comment by andrewfb** [comment]
Hey - this is actually by design to prevent a user from accidentally taking a temporary by reference. Under the hood we take the raw pointer of the VAO (to reduce the overhead of atomics stored on the vector of VAOs on Context).

**Comment by richardeakin** [comment]
I'm confused, how would passing by const& create a temporary, but non-const& wouldn't? Also, [Context::pushVao()](https://github.com/cinder/Cinder/blob/glNext/include/cinder/gl/Context.h#L108) is taking a const VaoRef & argument (there is also a variant that takes a raw pointer, but it is not used by ScopedVao and seems irrelevant to the argument of const correctness).

**Comment by andrewfb** [comment]
Doesn't create a temporary - but prevents taking a temporary by reference. Without it, `ScopedVao scp( makeMyVao() )` would be legal, but is dangerous since the VaoRef returned by `makeMyVao()` will not outlive the construction of the ScopedVao, and will likely crash mysteriously. Such a use case should be written as `gl::VaoRef vao = makeMyVao(); ScopedVao scpVao( vao );` and this arrangement (VaoRef& but not const VaoRef&) forces that.

**Comment by richardeakin** [comment]
I see. As an aside, and probably a moot point because it would be quite wasteful, we could add r-value reference constructors to support something like `ScopedVao( Vao::create() )`. Perhaps better to make using temporary Vao's a bit difficult.

**Comment by sansumbrella** [comment]
Gotcha. A bit annoying when making `draw()` methods const, since we need to store `VaoRef`. Would be good to document this design choice inline for the future.

**Comment by richardeakin** [comment]
@sansumbrella's point seems to push the favor towards adding an additional && constructor. But then, we're talking Vao here, are we really gaining some performance by not storing a shared_ptr for the life of the RAII object?

**Pull request closed without merging**
