### PR TITLE
Thyrrestrup vert batch cleanup

### PR DESCRIPTION
**Pull request by richardeakin**
This is the commit from #1370 to fix VertBatch on rasberry pi, which I prematurely merged.

### CODE REVIEW

**Comment by richardeakin** [comment]
Also, tested on windows and indeed this fixes a crash when using `gl::VertBatch::create( GL_POINTS, true )`.

For repro test here: http://pastebin.com/w82E31ph

**Comment by thyrrestrup** [comment]
hi @richardeakin
Please don't merge this - my name is spelled wrong ;-)
I've created a new PR and fixed a couple of whitespace issues.

**Comment by andrewfb** [comment]
Thanks for this fix

**Comment by thyrrestrup** [comment]
NP ;-)

**Pull request merged**
