### PR TITLE
enumerated parameters with callbacks

### PR DESCRIPTION
**Pull request by gaborpapp**
Added enumerated parameters with accessors for partly solving #444. Please revise.

### CODE REVIEW

**Comment by richardeakin** [comment]
Thanks for this work.  As it currently stands, the `Options<int>` passed back is going to cause problems, since it maps to TW_TYPE_INT32 ([here](https://github.com/cinder/Cinder/blob/master/src/cinder/params/Params.cpp#L623)). The easiest solution would be to disallow the chained options for enum param /w callbacks, users would then have to use the optionsStr to do things like specify keyUp, keyDown, or group. This seems OK to me since its where we are currently at anyway.

The other, messier, solution would be to somehow store on the Options that it needs to be added with TwDefineEnum. We'd need to store the vector<string> on Options, too..

**Comment by richardeakin** [comment]
Well I'll be tickled pink, this does work and works well.  I don't actually see any limitations here.

I've pushed a branch that adds an overload for use with updateFn(), as well as some sample code to ParamsBasic. Sweet!

**Comment by gaborpapp** [comment]
Great! Thanks! And what is the situation with the TW_TYPE_INT32 mapping? Does this really get mapped and it works because int is 32-bit in OS X and Windows in 32 and 64-bit as well?

**Comment by richardeakin** [comment]
On Mac it is built as 64-bit and working there, but yes we should test on both windows 32-bit and 64-bit before merging that branch.  Tell you the truth I'm not entirely sure how it works, I guess once you TwDefineEnum then ATB remembers that even when it is removed and re-added later from an `Options<T>`.

**Comment by richardeakin** [comment]
Merged after testing here and working on both 32-bit and 64-bit windows. Now the new callback stuff should be pretty complete, which is great.

**Comment by gaborpapp** [comment]
Awesome! Thanks Rich!

**Pull request merged**
