### PR TITLE
Added more information to OSX building from git

### PR DESCRIPTION
**Pull request by jessamynsmith**
Updated OSX installation instructions to include information about how to install and link to required libraries.

### CODE REVIEW

**Comment by richardeakin** [comment]
Thanks for this, however we ship a copy of oggvorbis and it is built into the libcinder.a binary. Boost is also shipped, in the form of a submodule for headers and binaries within the lib file. So you shouldn't need to install these libraries via `homebrew`, not for cinder anyway.

**Comment by jessamynsmith** [comment]
I was attempting to follow the instructions given for "Building on OS X". This is the error I observed:

```
$ sh fullbuild.sh 
=== BUILD TARGET cinder OF PROJECT cinder WITH CONFIGURATION Release ===

Check dependencies

CompileC build/cinder.build/Release/cinder.build/Objects-normal/x86_64/RendererImpl2dMacQuartz.o /Users/jessamyn/Development/codementor/Cinder/src/cinder/app/cocoa/RendererImpl2dMacQuartz.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/jessamyn/Development/codementor/Cinder/xcode
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -arch x86_64 -fmessage-length=156 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=c++11 -stdlib=libc++ -Wno-trigraphs -fpascal-strings -O3 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Wunreachable-code -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -Wno-c++11-extensions -DNDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fasm-blocks -ffast-math -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -mmacosx-version-min=10.8 -g -fvisibility-inlines-hidden -Wno-sign-conversion -iquote /Users/jessamyn/Development/codementor/Cinder/xcode/build/cinder.build/Release/cinder.build/cinder-generated-files.hmap -I/Users/jessamyn/Development/codementor/Cinder/xcode/build/cinder.build/Release/cinder.build/cinder-own-target-headers.hmap -I/Users/jessamyn/Development/codementor/Cinder/xcode/build/cinder.build/Release/cinder.build/cinder-all-target-headers.hmap -iquote /Users/jessamyn/Development/codementor/Cinder/xcode/build/cinder.build/Release/cinder.build/cinder-project-headers.hmap -iquote../include -iquote../src/oggvorbis/vorbis -iquote../src/r8brain -I/Users/jessamyn/Development/codementor/Cinder/lib/include -I../include -I../include/macosx/png -I../include/macosx/cairo -I../include/jsoncpp -I../include/oggvorbis -I/Users/jessamyn/Development/codementor/Cinder/xcode/build/cinder.build/Release/cinder.build/DerivedSources/x86_64 -I/Users/jessamyn/Development/codementor/Cinder/xcode/build/cinder.build/Release/cinder.build/DerivedSources -F/Users/jessamyn/Development/codementor/Cinder/lib -include /var/folders/qm/c08qp2dj2h52n5rxnnjj1_jh0000gn/C/com.apple.DeveloperTools/7.3.1-7D1014/Xcode/SharedPrecompiledHeaders/cinder_Prefix-bipgpcrmeiyaytctodikfqsfedwk/cinder_Prefix.pch -MMD -MT dependencies -MF /Users/jessamyn/Development/codementor/Cinder/xcode/build/cinder.build/Release/cinder.build/Objects-normal/x86_64/RendererImpl2dMacQuartz.d --serialize-diagnostics /Users/jessamyn/Development/codementor/Cinder/xcode/build/cinder.build/Release/cinder.build/Objects-normal/x86_64/RendererImpl2dMacQuartz.dia -c /Users/jessamyn/Development/codementor/Cinder/src/cinder/app/cocoa/RendererImpl2dMacQuartz.mm -o /Users/jessamyn/Development/codementor/Cinder/xcode/build/cinder.build/Release/cinder.build/Objects-normal/x86_64/RendererImpl2dMacQuartz.o
In file included from /Users/jessamyn/Development/codementor/Cinder/src/cinder/app/cocoa/RendererImpl2dMacQuartz.mm:24:
In file included from ../include/cinder/app/cocoa/RendererImpl2dMacQuartz.h:24:
In file included from ../include/cinder/app/AppBase.h:28:
In file included from ../include/cinder/app/Platform.h:26:
In file included from ../include/cinder/DataSource.h:28:
In file included from ../include/cinder/Url.h:26:
In file included from ../include/cinder/Stream.h:28:
../include/cinder/Filesystem.h:35:11: fatal error: 'boost/filesystem.hpp' file not found
        #include <boost/filesystem.hpp>
                 ^
1 error generated.
```

I was able to get past the error by installing the required libraries and specifying them in the build command. Is there a more acceptable solution? If so, I think the instructions should be updated.

**Comment by gaborpapp** [comment]
Did you clone cinder with submodules? If there are no files in `include/boost` you need to initialise submodules like this:

    git submodule update --init

**Comment by jessamynsmith** [comment]
Thank you, @gaborpapp, that was indeed the issue. I think the docs could be clearer. I see that the clone command with --recursive is present, but because it's under "Installing Git" (and I already have git) I didn't see it. It would make more sense to me to have the instructions for cloning the project under a separate, descriptive heading. Or at least modify the headings to reflect the fact that the sections are in fact about installing git and cloning Cinder. In any case, I think it would be worth noting in the "Building" sections that you need to have submodules, since git doesn't retrieve them by default.

**Comment by jessamynsmith** [comment]
Even better, the build script itself could error out if submodules are missing, with an error telling the user what to do. I'm happy to make that change and submit a PR if you like.

**Comment by richardeakin** [comment]
What docs did you look at when trying to find build instructions?  The main [README](https://github.com/cinder/Cinder/blob/e7ea5d98f64048fe0cd62d51cfa8459128021ee1/README.md) warns you that we use submodules.

I think having a build script that checked for missing files would be a bit overkill, and it would be maintenance heavy. The scripts are platform specific and who knows what the deps will be in the future. Improving docs is the way to go IMO.

**Comment by richardeakin** [comment]
> I was attempting to follow the instructions given for "Building on OS X". This is the error I observed...

From what I can tell, you're referring to [this guide](https://libcinder.org/docs/guides/mac-setup/index.html), which directs users to the [Cinder + Git] guide in the second paragraph. This one has some errors and can be improved in a couple obvious ways, so I'll open an issue for that.

**Comment by richardeakin** [comment]
Actually the guide in master branch has the errors I was thinking of fixed, so I just opened #1516 to  address the clarification needed for submodules.

**Pull request closed without merging**
