### PR TITLE
When updating a texture from a PBO, Mipmaps were not updated. 

### PR DESCRIPTION
**Pull request by ChristophPacher**
When updating a texture from a PBO, Mipmaps were not updated.

### CODE REVIEW

**Comment by ChristophPacher** [comment]
Just saw that I included the merge from the upstream changes into my fork. will submit a new pullrequest..

**Comment by ChristophPacher** [comment]
Just saw that I included the merge from the upstream changes into my fork. will submit a new pullrequest..

**Comment by ChristophPacher** [comment]
I tried to create a new PR without the commit 953a5da but was not able to do so via the web interface. Is this even possible?

**Comment by andrewfb** [comment]
Thanks - I went ahead and just merged this manually 46a52f841963e6604cb12af6063c3a6999e80fff

**Pull request closed without merging**
