### PR TITLE
Osc update constructors

### PR DESCRIPTION
**Pull request by ryanbartley**
Addresses suggestion from #1500.

### CODE REVIEW

**Comment by ryanbartley** [comment]
This branch should be ready for merge.

**Comment by richardeakin** [comment]
This was rebased and merged as cce030fb2b544070378661ba040a99bcc394f486

**Comment by ryanbartley** [comment]
unfortunately, the "Updated constructors to match between protocols wasn't in the last merge. I screwed up my ordering.

**Comment by ryanbartley** [comment]
Possible that we should revert the last one and merge this one.

**Comment by richardeakin** [comment]
Isn't it in the commit I linked to above? Let me know if we're still missing something.

**Comment by ryanbartley** [comment]
Yeah. I was incorrect. Didn't realize you pulled it in separately.

**Pull request closed without merging**
