### PR TITLE
Perform line continuation logic in ObjLoader.

### LINKED ISSUE #1121: ObjLoader fails to parse OBJ files with line continuations marked by `\`
When loading OBJ files that break vertex or face properties across multiple lines, parsing fails with an exception: `stoi: no conversion`.

Example problematic line (note the trailing `\` to indicate continuation on the following line):
```
f 27050/26938/27050 27041/26929/27041 27044/26932/27044 \
 27047/26935/27047
```

OSX Finder and Unity3D both parse the OBJ successfully, so I would expect the Cinder parser to handle this, too.

### PR DESCRIPTION
**Pull request by sansumbrella**
Closes #1121

### CODE REVIEW

**Comment by richardeakin** [comment]
Will this work if the `next` line also ends with a `\` continuation char? Example from [here](http://www.martinreddy.net/gfx/3d/OBJ.spec):

```
cstype bmatrix
	deg 3 3
	step 3 3
	bmat u  1       -3      3       -1      \
		0       3       -6      3       \
		0       0       3       -3      \
		0       0       0       1
	bmat v  1       -3      3       -1      \
		0       3       -6      3       \
		0       0       3       -3      \
		0       0       0       1
```

**Comment by sansumbrella** [comment]
Good catch. Yes.

Also added a check in case someone has a really poorly formatted file that ends with `\`. Not sure how critical that is.

**Comment by paulhoux** [comment]
Ola, will this also work if there is empty space after the ```\```?

**Comment by sansumbrella** [comment]
@paulhoux no it won't. Gotta love edge cases.

**Comment by sansumbrella** [comment]
There isn't a `strip(const std::string &str)` function in cinder now by any chance?

**Comment by richardeakin** [comment]
Do we need to support trailing whitespace? C preprocessor doesn't.

**Comment by sansumbrella** [comment]
For now, I would opt to not support whitespace after the line continuation.

OSX Finder does manage to parse the OBJ with pathological whitespace. But trimming trailing whitespace is pretty lowhanging fruit for someone in control of an OBJ (where knowing there may be line continuations somewhere in your file is less so; and they may help a lot with human readability).

A bigger question: if we handle trailing whitespace after the line continuation marker, what do we do with it? Keep it as the start of the next line? Trim it and throw it away? What if there we other trailing characters other than whitespace?

**Comment by paulhoux** [comment]
If trailing white space is not common in OBJ files, I have no problem if we don't support it here. There currently is no ```trim()``` method in Cinder, but there is in Boost and you can find a cross-platform solution here: http://stackoverflow.com/questions/216823/whats-the-best-way-to-trim-stdstring

**Comment by sansumbrella** [comment]
Yeah, I didn't want to pull in the boost hammer since my understanding is we're trying to move away from it.

It seems like the line continuations themselves aren't all that common (since no one has reported an OBJ that broke the loader this way before). But some combo of 3DS and Rhino managed to create them.

**Comment by sansumbrella** [comment]
This is ready to merge and solves problems I have encountered with OBJ files exported from Rhino.

Added unit tests for the OBJ parsing which helped narrow down where the crash was happening (and where line continuations resulted in wrong vertex data). Modifications to OBJ loader pass the new tests.

**Comment by richardeakin** [comment]
Sorry for the delay, everything looks good here, thanks for the updates..

**Pull request merged**
