### PR TITLE
Texture::setData now respects internal format

### PR DESCRIPTION
**Pull request by m1keall1son**
If i wanted to create a one channel 16u texture (often the case for depth textures) and access it in the shader as a usampler2D, cinder automatically defaulted to GL_RED in the Texture::update method, breaking the ability to sampler the texture at all if it was not initialized with type GL_RED

Now the internal format is checked and the correct dataFormat is used.

### CODE REVIEW

**Comment by m1keall1son** [comment]
oh also theres the test case in the test/_opengl dir :)

**Comment by richardeakin** [comment]
Along with that test, I see a [500k icon checked in](https://github.com/cinder/Cinder/pull/848/files#diff-9288b54be0475a2c8360eafa9ce4a7cd). Can you remove this? The rule of thumb is to reference the icons in samples/data, though for tests they don't need icons since they are only for, well, testing.

**Comment by m1keall1son** [comment]
oops!  its removed.

**Comment by andrewfb** [comment]
Rich just pointed out this PR includes test/_opengl/VolumeKinect - was that intentional? I will remove it if not.

**Comment by m1keall1son** [comment]
Ah fuck that's an accident plz remove

**Comment by m1keall1son** [comment]
But could be a cool sample at some point haha

**Comment by richardeakin** [comment]
Yea I was thinking perhaps add it to the kinect block's repo if if it seems usefult for others.

**Comment by m1keall1son** [comment]
its not far enough along enough for that unfortunately

**Pull request merged**
