### PR TITLE
DeferredShading sample optimizations

### PR DESCRIPTION
**Pull request by BanTheRewind**
Bug fixes and improved performance.

### CODE REVIEW

**Comment by BanTheRewind** [comment]
Don't merge juuuuust yet. Working on instances drawing for the lights and shadow casters to eek out a couple or few more FPS.

**Comment by richardeakin** [comment]
I think this is not ready to merge still? I just tried running DeferredShading sample and noticed #787 issue persists, also DeferredShadingAdvanced sample is throwing an error in the DOF fragment shader:

```
Depth of field: GLSL Error: FRAGMENT: ERROR: 0:31: Incompatible types (float and vec4) in assignment (and no available implicit conversion)
ERROR: 0:45: Incompatible types in initialization (and no available implicit conversion)
...
```

**Comment by BanTheRewind** [comment]
I wonder if I just accidentally left the updated version of the DoF shader out of the commit. Will check when I get home tonight. 




This update doesn't fix the scrambled image issue (which I haven't been able to reproduce to debug, unfortunately), but the advanced sample runs about 20-25% faster with nicer looking shadows. It also removes any code from the basic sample left over from the advanced (ie, loading the "random" texture, setting a uniform block binding, etc).

**Comment by BanTheRewind** [comment]
Shader issue on the advanced sample fixed. Just needed to commit files. Didn't realize they'd been left out.

**Comment by BanTheRewind** [comment]
Fixed that bug. Just needed to set alpha to 1.0 in the point light fragment shader. That pass uses additive blending, so it makes sense that it was going wonky. The advanced sample doesn't have an alpha channel in the ping=pong FBO, which is why the problem doesn't happen there. I'm using the alpha channel the basic sample's G-buffer to store emission data to render the light sources.

**Comment by BanTheRewind** [comment]
OK. Bug is fixed for the Iris integrated card now, too. I've also switched all the drawing routines to use batches. This makes the ::draw() method a little more compact and easier to read.

**Comment by richardeakin** [comment]
Yep, iris bug fix confirmed. Also, I'm seeing 60fps on the advanced sample - nice work!

**Pull request merged**
