### PR TITLE
Added supplementary html for LoggerFile and LoggerFileRotating

### PR DESCRIPTION
**Pull request by lucasvickers**
Added some supplementary html for the LoggerFile and LoggerFileRotating classes

### CODE REVIEW

**Comment by lucasvickers** [comment]
@gregkepler formatting updated based on your comments to #1149.  Let me know if you have any other comments.

**Comment by richardeakin** [comment]
Is this still needed in addition to #1149?

**Comment by lucasvickers** [comment]
This is supplementary html that gets pulled into the class reference, so it's different then #1149 which was a standalone guide.

**Comment by richardeakin** [comment]
Happy to merge this, although I think something still needs to be added to [this page](https://libcinder.org/docs/branch/master/guides/index.html) for the logging guide to show up - should we try to get both in at that point?

**Comment by gregkepler** [comment]
Yeah, it will need to be linked up from the Guides page. Not sure if it makes sense to be under "Working with Cinder" or "Cinder APIs".

**Comment by richardeakin** [comment]
I think Cinder APIs makes more sense, since this generally how you use different modules within ci::. The 'Working with Cinder' section is more conceptual, from what I see.

**Pull request merged**
