### PR TITLE
Android and Linux port

### PR DESCRIPTION
**Pull request by chaoticbob**
Android and Linux port of Cinder.

### CODE REVIEW

**Comment by ryanbartley** [comment]
Excited!

**Comment by paulhoux** [comment]
Epic!

**Comment by brucelane** [comment]
yes!

**Comment by andrewfb** [comment]
Obviously this is huge - thanks Hai. My intention is to create an android_linux branch before EOD today where this will live for the immediate future.

**Comment by notlion** [comment]
:+1: :joy:

**Pull request closed without merging**
