### PR TITLE
PolyLine should accept closed at initialization

### PR DESCRIPTION
**Pull request by drewish**
This let's me simplify some code like:
```c++
ci::PolyLine2f BuildingPlan::triangle()
{
    ci::PolyLine2f result( { ci::vec2(10, -10), ci::vec2(10, 10), ci::vec2(-10, 10), ci::vec2(10, -10)  } );
    result.setClosed();
    return result;
}
```

Down to a one liner.
```c++
ci::PolyLine2f BuildingPlan::triangle()
{
    return ci::PolyLine2f( { ci::vec2(10, -10), ci::vec2(10, 10), ci::vec2(-10, 10), ci::vec2(10, -10)  }, true );
}
```

### CODE REVIEW

**Comment by mottosso** [comment]
I personally really like the named parameter idiom spread across Cinder. Could that work here?

```cpp
ci::PolyLine2f BuildingPlan::triangle()
{
    return ci::PolyLine2f( { ci::vec2(10, -10), ci::vec2(10, 10), ci::vec2(-10, 10), ci::vec2(10, -10)  } ).closed(true);
}
```

Though it should probably apply to the other arguments too.

**Comment by drewish** [comment]
@mottosso yeah that's actually a nice pattern to follow, it'd be backwards compatible if we left the other methods in place.

**Comment by richardeakin** [comment]
I also prefer a named method rather than additional bool as argument, because it is clearer at the call site. That said, I don't believe the classes like Polyline, Shape2d, are currently using the named parameter idiom, not that they shouldn't but need to weigh whether we want to start introducing methods in that fashion there.

**Comment by andrewfb** [comment]
I'm inclined to accept this as written. I'm not opposed to NPI in instances like this, but it does feel like a policy that needs to revisited on a larger scale at some future date.

**Pull request merged**
