### PR TITLE
Fix macOS/iOS builds

### LINKED ISSUE #2179: Build error on macOS 10.15.5 Xcode 11.5
Steps taken:

```
% git clone --recursive git://github.com/cinder/Cinder.git cinder_master
% cd cinder_master/proj/xcode
% ./fullbuild.sh
```

Lots of normal build output that ends with:

```
Libtool /Users/howes/src/cinder_master/lib/macosx/Debug/libcinder.a normal x86_64 (in target 'cinder' from project 'cinder')
    cd /Users/howes/src/cinder_master/proj/xcode
    export MACOSX_DEPLOYMENT_TARGET=10.8
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only x86_64 -D -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -L/Users/howes/src/cinder_master/lib/macosx/Debug -filelist /Users/howes/src/cinder_master/proj/xcode/build/cinder.build/Debug/cinder.build/Objects-normal/x86_64/cinder.LinkFileList -framework AppKit -framework Cocoa -framework OpenGL -framework QTKit -framework CoreVideo -framework CoreGraphics -framework ApplicationServices -framework ScreenSaver -framework AudioToolbox -framework AudioUnit -framework CoreAudio -dependency_info /Users/howes/src/cinder_master/proj/xcode/build/cinder.build/Debug/cinder.build/Objects-normal/x86_64/cinder_libtool_dependency_info.dat -o /Users/howes/src/cinder_master/lib/macosx/Debug/libcinder.a

** BUILD SUCCEEDED **

Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project /Users/howes/src/cinder_master/proj/xcode/cinder.xcodeproj -target cinder_iphone -configuration Release -sdk iphoneos

Build settings from command line:
    SDKROOT = iphoneos13.5

note: Using new build system
note: Planning build
note: Constructing build description
error: AppKit is not available when building for iOS. (in target 'cinder_iphone' from project 'cinder')
error: Cocoa is not available when building for iOS. (in target 'cinder_iphone' from project 'cinder')

** BUILD FAILED **

Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project /Users/howes/src/cinder_master/proj/xcode/cinder.xcodeproj -target cinder_iphone -configuration Debug -sdk iphoneos

Build settings from command line:
    SDKROOT = iphoneos13.5

note: Using new build system
note: Planning build
note: Constructing build description
error: AppKit is not available when building for iOS. (in target 'cinder_iphone' from project 'cinder')
error: Cocoa is not available when building for iOS. (in target 'cinder_iphone' from project 'cinder')

** BUILD FAILED **

Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project /Users/howes/src/cinder_master/proj/xcode/cinder.xcodeproj -target cinder_iphone_sim -configuration Release -sdk iphonesimulator

Build settings from command line:
    SDKROOT = iphonesimulator13.5

note: Using new build system
note: Planning build
note: Constructing build description
warning: Product libcinder.a cannot weak-link framework CoreVideo.framework (in target 'cinder_iphone_sim' from project 'cinder')
warning: Product libcinder.a cannot weak-link framework AVFoundation.framework (in target 'cinder_iphone_sim' from project 'cinder')
warning: Product libcinder.a cannot weak-link framework CoreMedia.framework (in target 'cinder_iphone_sim' from project 'cinder')
warning: Product libcinder.a cannot weak-link framework CoreVideo.framework (in target 'cinder_iphone_sim' from project 'cinder')
warning: Product libcinder.a cannot weak-link framework AVFoundation.framework (in target 'cinder_iphone_sim' from project 'cinder')
warning: Product libcinder.a cannot weak-link framework CoreMedia.framework (in target 'cinder_iphone_sim' from project 'cinder')
error: AppKit is not available when building for iOS Simulator. (in target 'cinder_iphone_sim' from project 'cinder')
error: Cocoa is not available when building for iOS Simulator. (in target 'cinder_iphone_sim' from project 'cinder')
error: QTKit is not available when building for iOS Simulator. (in target 'cinder_iphone_sim' from project 'cinder')

** BUILD FAILED **

Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project /Users/howes/src/cinder_master/proj/xcode/cinder.xcodeproj -target cinder_iphone_sim -configuration Debug -sdk iphonesimulator

Build settings from command line:
    SDKROOT = iphonesimulator13.5

note: Using new build system
note: Planning build
note: Constructing build description
warning: Product libcinder.a cannot weak-link framework CoreVideo.framework (in target 'cinder_iphone_sim' from project 'cinder')
warning: Product libcinder.a cannot weak-link framework AVFoundation.framework (in target 'cinder_iphone_sim' from project 'cinder')
warning: Product libcinder.a cannot weak-link framework CoreMedia.framework (in target 'cinder_iphone_sim' from project 'cinder')
warning: Product libcinder.a cannot weak-link framework CoreVideo.framework (in target 'cinder_iphone_sim' from project 'cinder')
warning: Product libcinder.a cannot weak-link framework AVFoundation.framework (in target 'cinder_iphone_sim' from project 'cinder')
warning: Product libcinder.a cannot weak-link framework CoreMedia.framework (in target 'cinder_iphone_sim' from project 'cinder')
error: AppKit is not available when building for iOS Simulator. (in target 'cinder_iphone_sim' from project 'cinder')
error: Cocoa is not available when building for iOS Simulator. (in target 'cinder_iphone_sim' from project 'cinder')
error: QTKit is not available when building for iOS Simulator. (in target 'cinder_iphone_sim' from project 'cinder')

** BUILD FAILED **
```

### PR DESCRIPTION
**Pull request by bradhowes**
- Updated projects to use ARC (automatic reference counting)
- Removed non-ARC constructs

Fixes #2179

### CODE REVIEW

**Comment by lydhr** [comment]
Also change these two following settings (target iPhoneX):

##### CPU Architecture
- Error Message:
`Ignoring file ../../../..//lib/ios/Debug/libcinder.a, building for iOS-arm64 but attempting to link with file built for iOS-armv7
`
- Solution: ONLY_ACTIVE_ARCH = NO;


##### ENABLE_BITCODE
- Error Message:
`ld: '../../../..//lib/ios/Debug/libcinder.a(libcinder.a-armv7-master.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.
`
- Solution: ENABLE_BITCODE = YES;

**Comment by Morpheu5** [comment]
Hey, I was having [this problem here](https://discourse.libcinder.org/t/ios-static-libraries-gone-from-0-9-1-2/1700) with a missing `libcinder.a` file. This PR solves the problem for me. I was able to do a `fullbuild.sh` and compile my apps against the resulting `libcinder.a`. I merge upstream master into Brad's `branch1` and repeated the process without a hitch (a visible one, at least). Can someone give this some love?

**Comment by vinjn** [comment]
@andrewfb @paulhoux can you review / redirect?

**Comment by andrewfb** [comment]
Sorry for the delay on this and thanks for this @bradhowes - merged.

**Pull request merged**
