### PR TITLE
Added a drawStrokedCircle that supports a lineWidth setting.

### PR DESCRIPTION
**Pull request by paulhoux**
In response to https://forum.libcinder.org/#Topic/23286000002349013 , I have created a version of ```drawStrokedCircle``` that supports an arbitrary line width. It creates a triangle strip instead of a line loop. 

I should not have to mention that for line width values smaller than 1.0, you need proper (msaa) sub-sampling to make it look good.

### CODE REVIEW

**Comment by ryanbartley** [comment]
Is there a way this could go into the geom::WireCircle?

**Comment by richardeakin** [comment]
I think the design choice is that Wire* objects create line geometry, or in other words geometry suitable for GL_LINES. We were thinking that perhaps a `geom::Disk` or `geom::Ring` would be more suitable for that task. My vote for namig is Ring, but either would work.

I think if we were to go that route, I still like the idea of using gl::drawStrokedCircle() as the convenient way to use it, since it will be easy to find once you are used to the naming pattern of those methods (whereas gl::drawRing() would be harder to understand).

**Comment by andrewfb** [comment]
I agree with the geom::Ring idea as a nice additional piece of functionality, and then keeping drawStrokedCircle() variant that takes a `lineWidth` as the convenience entry point. Ryan just did something similar w/ geom::RoundedRect. It also helps us maintain the "only use convenience methods for convenience - upgrade to Batch / geom:: variants when perf matters" philosophy.

**Comment by BanTheRewind** [comment]
Nice addition. In my old MeshHelper block I had this as "ring", so that gets my vote, as well.  :)

**Comment by paulhoux** [comment]
OK, ```geom::Ring``` added and its convenience method is using it, too. Also fixed an issue with ```WireCircle``` (didn't draw at all, due to missing pointer increment) and ```geom::Rect``` (incorrect polygon winding).

**Pull request merged**
