### PR TITLE
Improve guide for building docs

### PR DESCRIPTION
**Pull request by drewish**
After #1245 I had a thoughts on how we could improve the docs building guide.

### CODE REVIEW

**Comment by drewish** [comment]
@gregkepler I'd love your thoughts on this. I'm also curious if there's a way to just build part of the docs. As I was making changes to the guide it was frustrating to have to wait a minute or two for the entire docs set to update before I could see my changes.

**Comment by drewish** [comment]
Thinking it might be good to mention that you can install it on OS X using homebrew: `brew install doxygen --with-doxywizard`

**Comment by gregkepler** [comment]
Hi @drewish. Yes, there are some shortcuts for generating docs that I could have sworn I documented, but somehow never made it in. I'll commit a paragraph with those shortcuts asap. 
Sorry I missed that.

**Comment by gregkepler** [comment]
Oh, they are in there, just on a different page...
https://libcinder.org/docs/guides/docs/documenting_cinder.html#generation

Perhaps they should be referenced in the Build Docs guide as well.
Hope that helps.

**Comment by gregkepler** [comment]
Hey @drewish, If there wasn't anything else that you wanted to add, we're ready to merge this.

**Comment by drewish** [comment]
It should be good to go. We can do follow ups for anything else.

**Comment by drewish** [comment]
Actually, I do have some other ideas that might be good to try to merge in:
- Explain how to build docs entirely on the command line
- Add a summary at the end and link it into the documenting cinder guide

I've also been playing around trying to automate some of hte build process so I can make changes and see them in the browsers quicker.

**Comment by gregkepler** [comment]
That sounds great. Let me know if there's anything I can help with or if there's anything I can clarify with the build process. Exciting to see what you come up with as far as further automating the build process. 

I don't have a ton of extra time to work on this myself at the moment, but happy to chip in here and there when I do have a few minutes.

**Comment by richardeakin** [comment]
@drewish should we merge this and you can submit any additions in a new PR?

**Comment by drewish** [comment]
Yeah that probably makes the most sense considering the fact that I haven't gotten back to this in the last couple weeks

**Pull request merged**
