### PR TITLE
CMake cinderMakeApp fix

### PR DESCRIPTION
**Pull request by ryanbartley**
Fixed small problem with feeding Blocks as absolute paths to the Blocks argument of cinderMakeApp

### CODE REVIEW

**Comment by richardeakin** [comment]
This is the 'absolute directory' option that was recently introduced, right?

Fix seems good to me, other than the formatting should be consistent.

**Comment by ryanbartley** [comment]
ah, that's brutal. I'll fix it.

**Comment by ryanbartley** [comment]
Alright, should be fixed now.

**Comment by richardeakin** [comment]
Thanks!

**Pull request merged**
