### PR TITLE
Replace deprecated OS X power management API use

### PR DESCRIPTION
**Pull request by pizthewiz**
`UpdateSystemActivity()` is deprecated as of OS X 10.8 and the recommended IOKit replacement `IOPMAssertionCreateWithName ` works on Mac OS X 10.6 and later.

Separate power management assertions are required to prevent idle system sleep and idle display sleep and as such this complicates the `isPowerManagementEnabled` situation - to prevent leaking power management assertions look to see if both are valid and report that, this should allow power management to be disabled and attempt to re-enable while the opposite situation would leak an assertion (though they get cleaned up at app quit time). 

Power assertions can be checked via:
```sh
$ pmset -g assertions
```

**NOTE**: OS X applications will need to link to _IOKit.framework_

### CODE REVIEW

**Comment by pizthewiz** [comment]
I'd be happy to update the Tinderbox project template and existing sample projects if this change will be accepted - should those changes be made on this PR?

**Comment by andrewfb** [comment]
In the past I've held off on this change and one to parse display names due to uncertainty on how it impacts application link times. Any insight into the reality of that situation?

**Comment by pizthewiz** [comment]
Good question, I'd like to say the linking time difference is negligible, but let me run a couple of Cinder and app compiles to compare.

**Comment by pizthewiz** [comment]
The link time difference doesn't seem substantial, less than half a second in my measurement. Here are some build timings for 18bdbcc54a2b342b01051d2a28a8f8df9b6d5164 (HEAD of this PR) vs branch's parent b8824b08dbf6b6e9941bf60fb317146c67d5ab16. Each execution, an untimed project clean is performed prior to build. This was run on an 8-core late 2009 2.8 GHz Intel Core i7 iMac (iMac11,1) with 16GB of RAM running Xcode 6.3.1.

## Averaged Values Over 3 Runs

### cinder.xcodeproj
 | Config | User  | System | CPU | Total
 ------------ | ------------ | ------------: | ------------: | ------------: | ------------:
18bdbcc54a2b342b01051d2a28a8f8df9b6d5164 | Debug | 451.37  | 30.48 | 722% | 1:06.71
b8824b08dbf6b6e9941bf60fb317146c67d5ab16 | Debug | 451.28  | 30.48 | 724% | 1:06.48
18bdbcc54a2b342b01051d2a28a8f8df9b6d5164 | Release | 555.06  | 31.92 | 742% | 1:18.99
b8824b08dbf6b6e9941bf60fb317146c67d5ab16 | Release | 554.51  | 31.87 | 742% | 1:18.99

### BasicApp.xcodeproj
 | Config | User  | System | CPU | Total
 ------------ | ------------ | ------------: | ------------: | ------------: | ------------:
18bdbcc54a2b342b01051d2a28a8f8df9b6d5164 | Debug | 13.64  | 0.51 | 156% | 9.06
b8824b08dbf6b6e9941bf60fb317146c67d5ab16 | Debug | 13.93 | 0.47 | 164% | 8.77
18bdbcc54a2b342b01051d2a28a8f8df9b6d5164 | Release | 11.75 | 0.44 | 174% | 6.99
b8824b08dbf6b6e9941bf60fb317146c67d5ab16 | Release | 11.56 | 0.43 | 176% | 6.81

## Data Gathering

Repo workingspace sitting at 18bdbcc54a2b342b01051d2a28a8f8df9b6d5164, the osx-power-management branch HEAD
```sh
$ git checkout osx-power-management
$ PROJECT=xcode/cinder.xcodeproj; repeat 3 \
xcodebuild > /dev/null -project $PROJECT -target cinder -configuration Debug clean &&
xcodebuild > /dev/null -project $PROJECT -target cinder -configuration Release clean &&
time xcodebuild > /dev/null -project $PROJECT -target cinder -configuration Debug &&
time xcodebuild > /dev/null -project $PROJECT -target cinder -configuration Release
xcodebuild -project $PROJECT -target cinder -configuration Debug > /dev/null  449.67s user 30.52s system 714% cpu 1:07.19 total
xcodebuild -project $PROJECT -target cinder -configuration Release > /dev/nul  553.34s user 31.96s system 741% cpu 1:18.88 total
xcodebuild -project $PROJECT -target cinder -configuration Debug > /dev/null  452.27s user 30.44s system 725% cpu 1:06.50 total
xcodebuild -project $PROJECT -target cinder -configuration Release > /dev/nul  556.48s user 31.81s system 743% cpu 1:19.08 total
xcodebuild -project $PROJECT -target cinder -configuration Debug > /dev/null  452.18s user 30.47s system 726% cpu 1:06.44 total
xcodebuild -project $PROJECT -target cinder -configuration Release > /dev/nul  555.36s user 31.98s system 743% cpu 1:19.01 total
```

BasicApp tweaked to enable power management and link to IOKit.framework
```sh
$ PROJECT=samples/BasicApp/xcode/BasicApp.xcodeproj; repeat 3 \
xcodebuild > /dev/null -project $PROJECT -configuration Debug clean &&
xcodebuild > /dev/null -project $PROJECT -configuration Release clean &&
time xcodebuild > /dev/null -project $PROJECT -configuration Debug &&
time xcodebuild > /dev/null -project $PROJECT -configuration Release
xcodebuild -project $PROJECT -configuration Debug > /dev/null  13.36s user 0.55s system 144% cpu 9.624 total
xcodebuild -project $PROJECT -configuration Release > /dev/null  11.56s user 0.44s system 164% cpu 7.290 total
xcodebuild -project $PROJECT -configuration Debug > /dev/null  13.94s user 0.50s system 167% cpu 8.627 total
xcodebuild -project $PROJECT -configuration Release > /dev/null  12.28s user 0.44s system 185% cpu 6.857 total
xcodebuild -project $PROJECT -configuration Debug > /dev/null  13.61s user 0.48s system 157% cpu 8.926 total
xcodebuild -project $PROJECT -configuration Release > /dev/null  11.42s user 0.44s system 174% cpu 6.806 total
```

BasicApp changes reverted and sitting at branch parent b8824b08dbf6b6e9941bf60fb317146c67d5ab16 
```sh
$ PROJECT=xcode/cinder.xcodeproj; repeat 3 \
xcodebuild > /dev/null -project $PROJECT -target cinder -configuration Debug clean &&
xcodebuild > /dev/null -project $PROJECT -target cinder -configuration Release clean &&
time xcodebuild > /dev/null -project $PROJECT -target cinder -configuration Debug &&
time xcodebuild > /dev/null -project $PROJECT -target cinder -configuration Release
xcodebuild -project $PROJECT -target cinder -configuration Debug > /dev/null  452.56s user 30.45s system 726% cpu 1:06.44 total
xcodebuild -project $PROJECT -target cinder -configuration Release > /dev/nul  553.88s user 31.85s system 742% cpu 1:18.86 total
xcodebuild -project $PROJECT -target cinder -configuration Debug > /dev/null  450.94s user 30.43s system 724% cpu 1:06.45 total
xcodebuild -project $PROJECT -target cinder -configuration Release > /dev/nul  554.75s user 31.80s system 741% cpu 1:19.08 total
xcodebuild -project $PROJECT -target cinder -configuration Debug > /dev/null  450.35s user 30.56s system 722% cpu 1:06.56 total
xcodebuild -project $PROJECT -target cinder -configuration Release > /dev/nul  554.91s user 31.96s system 742% cpu 1:19.03 total
$ PROJECT=samples/BasicApp/xcode/BasicApp.xcodeproj; repeat 3 \
xcodebuild > /dev/null -project $PROJECT -configuration Debug clean &&
xcodebuild > /dev/null -project $PROJECT -configuration Release clean &&
time xcodebuild > /dev/null -project $PROJECT -configuration Debug &&
time xcodebuild > /dev/null -project $PROJECT -configuration Release
xcodebuild -project $PROJECT -configuration Debug > /dev/null  13.76s user 0.49s system 153% cpu 9.283 total
xcodebuild -project $PROJECT -configuration Release > /dev/null  10.24s user 0.43s system 157% cpu 6.791 total
xcodebuild -project $PROJECT -configuration Debug > /dev/null  14.33s user 0.47s system 172% cpu 8.558 total
xcodebuild -project $PROJECT -configuration Release > /dev/null  12.11s user 0.43s system 184% cpu 6.797 total
xcodebuild -project $PROJECT -configuration Debug > /dev/null  13.71s user 0.46s system 167% cpu 8.477 total
xcodebuild -project $PROJECT -configuration Release > /dev/null  12.33s user 0.43s system 186% cpu 6.846 total
```

## Full Tables

### cinder.xcodeproj
18bdbcc54a2b342b01051d2a28a8f8df9b6d5164

 | User  | System | CPU | Total
 ------------ | ------------: | ------------: | ------------: | ------------:
Debug | 449.67  | 30.52 | 714% | 1:07.19
Debug | 452.27 | 30.44 | 725% | 1:06.50
Debug | 452.18 | 30.47 | 726% | 1:06.44
Release | 553.34  | 31.96 | 741% | 1:18.88
Release | 556.48 | 31.81 | 743% | 1:19.08
Release | 555.36 | 31.98 | 743% | 1:19.01

b8824b08dbf6b6e9941bf60fb317146c67d5ab16 

 | User  | System | CPU | Total
 ------------ | ------------: | ------------: | ------------: | ------------:
Debug | 452.56  | 30.45 | 726% | 1:06.44
Debug | 450.94 | 30.43 | 724% | 1:06.45
Debug | 450.35 | 30.56 | 722% | 1:06.56
Release | 553.88  | 31.85 | 742% | 1:18.86
Release | 554.75 | 31.80 | 741% | 1:19.08
Release | 554.91 | 31.96 | 742% | 1:19.03

### BasicApp.xcodeproj

18bdbcc54a2b342b01051d2a28a8f8df9b6d5164

 | User  | System | CPU | Total
 ------------ | ------------: | ------------: | ------------: | ------------:
Debug | 13.36 | 0.55 | 144% | 9.624
Debug | 13.94 | 0.50 | 167% | 8.627
Debug | 13.61 | 0.48 | 157% | 8.926
Release | 11.56 | 0.44 | 164% | 7.290
Release | 12.28 | 0.44 | 185% | 6.857
Release | 11.42 | 0.44 | 174% | 6.806

b8824b08dbf6b6e9941bf60fb317146c67d5ab16 

 | User  | System | CPU | Total
 ------------ | ------------: | ------------: | ------------: | ------------:
Debug | 13.76 | 0.49 | 153% | 9.283
Debug | 14.33 | 0.47 | 172% | 8.558
Debug | 13.71 | 0.46 | 167% | 8.477
Release | 10.24 | 0.43 | 157% | 6.791
Release | 12.11 | 0.43 | 184% | 6.797
Release | 12.33 | 0.43 | 186% | 6.846

**Comment by andrewfb** [comment]
Thanks for being so thorough on this. I'm inclined to go for it here, since Apple seems to be forcing our hand some with this, and it's probably not a feature worth pushing to a separate CinderBlock. As a bonus it opens up the possibility of pulling the name of Displays from the system, which can be handy for certain scenarios. I need to modify all the samples to reflect our upcoming Boost path change; I can roll this change in at the same time.

**Comment by pizthewiz** [comment]
The same power management capabilities are available in the [Cinder-AppNap](https://github.com/pizthewiz/Cinder-AppNap) CinderBlock, though it uses the 10.9+ `NSProcessInfo` activity APIs and is largely made obsolete by this PR. I've made that same display name change when searching for a Rift display to push an app's window to - want a PR for that too?

**Comment by richardeakin** [comment]
I'd also like a `Display::getName()`-like ability, and have [coded on Mac before](https://github.com/richardeakin/Cinder/commit/9a6e0ac1532aca30c8440c523d4b4d9457871a23) (well, more or less copy/pasted the code).  Though I do see display name reporting as a feature addtion, and one we shouldn't let hold up the upcoming big release, since the ideal way to do it means a cross-platform api, additions to `Platform` class and a matching impl on windows... work. :)

On the topic of adding IOKit framework, now would be an opportune time to do it as we're already adding a couple other new framework dependencies for this release (CoreMedia and AVFoundation, I believe).

**Comment by pizthewiz** [comment]
Funny that, I even looked into how we could do it on Windows (dangerous since I'm _definitely_ not a Windows developer) and found the [`GetMonitorInfo`](https://msdn.microsoft.com/en-us/library/windows/desktop/dd144901(v=vs.85).aspx) function:
```C++
BOOL GetMonitorInfo(
  _In_   HMONITOR      hMonitor,
  _Out_  LPMONITORINFO lpmi
);
```

which has an out param to a [`MONITORINFOEX `](https://msdn.microsoft.com/en-us/library/windows/desktop/dd145066(v=vs.85).aspx) structure pointer with a member of the display's name:
```C++
typedef struct tagMONITORINFOEX {
  DWORD cbSize;
  RECT  rcMonitor;
  RECT  rcWork;
  DWORD dwFlags;
  TCHAR szDevice[CCHDEVICENAME];
} MONITORINFOEX, *LPMONITORINFOEX;
```

not sure what the story is for WinRT though.

**Pull request merged**
