### PR TITLE
AxisAlignedBox vertex recalculation

### PR DESCRIPTION
**Pull request by lithium-snepo**
Let's try this again ;)
Addresses #864

### CODE REVIEW

**Comment by richardeakin** [comment]
This makes sense to me, though perhaps an implementation worth considering would be to mark the vertices as dirty and update them the next time that box.getSize() is called. This would mean if you add a list of vec3 points then you're only doing the recalculateVertices() once. This would be an optimization, so it could also be done at a later time than this bug fix as well..

**Comment by lithium-snepo** [comment]
This did occur to me but i thought given what I assumed to be a typical use case that it was probably unnecessary. If you think it's something that will end up getting added later, I might as well just add the optimization to this PR.

**Comment by lithium-snepo** [comment]
Ugh, i'm *terrible* at git. The fix has been made, but i need to work out this rebasing business.

**Comment by pizthewiz** [comment]
I've found the edX team's [How to Rebase a Pull Request](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) guide to be super helpful.

**Comment by lithium-snepo** [comment]
Thanks for that. I thought i had it working but I ended up just piling more and more shit into the branch, so I just bailed on it. I'll play around on some local repositories before I go committing willy-nilly to public ones in the future.

**Pull request closed without merging**
