### PR TITLE
change '>>' to '> >'

### PR DESCRIPTION
**Pull request by mofeing**
Building a cinder app gives the following error "a space is required between consecutive right angle brackets (use '> >')"

### CODE REVIEW

**Comment by andrewfb** [comment]
Hey - what compiler are you seeing this error with?

**Comment by mofeing** [comment]
@andrewfb clang++
I use `clang main.cpp -lcinder` and I got the headers and libcinder.a installed in the system's directories.

**Comment by simongeilfus** [comment]
Would adding `-std=c++11` help?

**Comment by mofeing** [comment]
@simongeilfus It worked!
Thanks.

**Pull request closed without merging**
