### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jasonsturges**
Use rawgit for SVG logo in README.

### CODE REVIEW

**Comment by richardeakin** [comment]
Interesting, I haven't ever seen any problems with the logo but then I don't see why we're linking through libcinder.org, either. However why not link to ./docs/htmlsrc/_assets/images/cinder_logo.svg relatively, seeing as how this README.md file lives in the same repo as the svg image?

**Comment by jasonsturges** [comment]
Weird, you don't see this?

screencapture

Maybe something to do with the redirect of the logo?

    $ curl -I http://libcinder.org/images/logo.png
    HTTP/1.1 301 Moved Permanently
    Server: nginx/1.4.6 (Ubuntu)
    Date: Thu, 15 Oct 2015 08:45:49 GMT
    Content-Type: text/html
    Content-Length: 193
    Connection: keep-alive
    Location: https://libcinder.org/images/logo.png

For some reason, relative path to SVGs defy a security policy at GitHub, and don't render.  In other repos, a common practice I've seen is linking through rawgit cdn.  

Definitely disregard if this is localized to my environment.

**Comment by lucasvickers** [comment]
I see the missing logo as well.

**Comment by pizthewiz** [comment]
I think the image is broken because the destination of the redirect (which the bowser should auto-follow) 404s:
```
🍔  curl -LI http://libcinder.org/images/logo.png
HTTP/1.1 301 Moved Permanently
Server: nginx/1.4.6 (Ubuntu)
Date: Thu, 15 Oct 2015 16:15:15 GMT
Content-Type: text/html
Content-Length: 193
Connection: keep-alive
Location: https://libcinder.org/images/logo.png

HTTP/1.1 404 NOT FOUND
Server: nginx/1.4.6 (Ubuntu)
Date: Thu, 15 Oct 2015 16:15:16 GMT
Content-Type: text/html
Content-Length: 233
Connection: keep-alive
```

That said, I do _not_ see the issue on my OS X 10.11 machine with Safari or Chrome (or Canary) and instead see the original image proxied by GitHub: https://camo.githubusercontent.com/9b81ef3f41fada717e864753073c6f382accaf6c/687474703a2f2f6c696263696e6465722e6f72672f696d616765732f6c6f676f2e706e67

I'm not sure why you don't see that proxied image too but the original image source URL is definitely incorrect and I'm all for replacing it with an SVG.

**Comment by lucasvickers** [comment]
I now see the image.  Strange.
I'm 10.10.4 and have been testing on Chrome 44

**Comment by jasonsturges** [comment]
Perhaps it's our location to the cdn - camo cache is a miss for me

    X-Served-By: cache-dfw1828-DFW
    X-Cache: MISS
    X-Cache-Hits: 0

For others, perhaps the nearest edge server retains a copy; or, maybe you are still within max-age before expiration of the cache.

You could try to purge your cache:

    $ curl -X PURGE https://camo.githubusercontent.com/9b81ef3f41fada717e864753073c6f382accaf6c/687474703a2f2f6c696263696e6465722e6f72672f696d616765732f6c6f676f2e706e67

**Comment by pizthewiz** [comment]
I think the `PURGE` worked, the proxied version is now dead ;0)

**Comment by justinbmartin** [comment]
Good catch! Instead of referencing the Github CDN url, make a quick modification to reference the repos SVG logo.
```
<img src="https://libcinder.org/docs/_assets/images/cinder_logo.svg" width="256" height="auto" alt="Cinder Logo"/>
```
Github internal will auto-cache that copy into their CDN, no need to reference their CDN directly.

**Comment by jasonsturges** [comment]
@justinbmartin Strangely that doesn't work - either your server does not host SVG with a content-type GitHub agrees with; or, GitHub disables that due to potential cross site scripting vulnerabilities.

From: https://libcinder.org/docs/_assets/images/cinder_logo.svg

    Content-Type: image/svg+xml

From: https://cdn.rawgit.com/cinder/Cinder/master/docs/htmlsrc/_assets/images/cinder_logo.svg

    Content-Type: image/svg+xml;charset=utf-8

Sorry for all the noise here - either a png, maybe a change to your mime-type, or use of a cdn would resolve the problem.  SVG looks nice on retina.  Shoot me a url; or, let me know - and if this is a hassle feel free to reject this pull request and handle it however you like.  

Just thought I'd help out instead of passing the issue along, but I don't want to create more overhead.

**Comment by pizthewiz** [comment]
It is definitely `Content-Type` related. If I use the libcinder.org SVG file URL into GitHub Markdown:
```Markdown
![Cinder Logo](https://libcinder.org/docs/_assets/images/cinder_logo.svg)
```
Cinder Logo

it of course gets proxied, but the proxy URL does *not* have a `Content-Type`:
```sh
🍔  curl -sS -I https://camo.githubusercontent.com/c1e98f5e7bb6c32561962988a0e2ec569d864f39/68747470733a2f2f6c696263696e6465722e6f72672f646f63732f5f6173736574732f696d616765732f63696e6465725f6c6f676f2e737667 | egrep Content-Type
X-Content-Type-Options: nosniff
```

Conversely, if I slap the rawgit.com URL in instead:
```Markdown
![Cinder Logo](https://cdn.rawgit.com/cinder/Cinder/master/docs/htmlsrc/_assets/images/cinder_logo.svg)
```
Cinder Logo
It *does*:
```sh
🍔  curl -sS -I https://camo.githubusercontent.com/56755f4291a868e88c4da7ee4f41cee9e60d3f35/68747470733a2f2f63646e2e7261776769742e636f6d2f63696e6465722f43696e6465722f6d61737465722f646f63732f68746d6c7372632f5f6173736574732f696d616765732f63696e6465725f6c6f676f2e737667 | egrep Content-Type
Content-Type: image/svg+xml;charset=utf-8
X-Content-Type-Options: nosniff
```

**Comment by jasonsturges** [comment]
The web is riddled with insanity.

End-to-end, I guess that:

- Rendered markdown uses [camo](https://camo.githubusercontent.com/56755f4291a868e88c4da7ee4f41cee9e60d3f35/68747470733a2f2f63646e2e7261776769742e636f6d2f63696e6465722f43696e6465722f6d61737465722f646f63732f68746d6c7372632f5f6173736574732f696d616765732f63696e6465725f6c6f676f2e737667), loaded from [rawgit.com](https://camo.githubusercontent.com/56755f4291a868e88c4da7ee4f41cee9e60d3f35/68747470733a2f2f63646e2e7261776769742e636f6d2f63696e6465722f43696e6465722f6d61737465722f646f63732f68746d6c7372632f5f6173736574732f696d616765732f63696e6465725f6c6f676f2e737667) (MaxCDN), loaded from [raw.githubusercontent.com](https://raw.githubusercontent.com/cinder/Cinder/master/docs/htmlsrc/_assets/images/cinder_logo.svg), which appears to work

- Rendered markdown says [camo](https://camo.githubusercontent.com/c1e98f5e7bb6c32561962988a0e2ec569d864f39/68747470733a2f2f6c696263696e6465722e6f72672f646f63732f5f6173736574732f696d616765732f63696e6465725f6c6f676f2e737667) is not found when loaded from [libcinder.org](https://libcinder.org/docs/_assets/images/cinder_logo.svg)

- Rendered markdown uses GitHub [absolute](https://raw.githubusercontent.com/cinder/Cinder/master/docs/htmlsrc/_assets/images/cinder_logo.svg) or relative paths directly, but fails to render


Something can't be right, here... because I can load a sample SVG from [w3.org](http://dev.w3.org/SVG/tools/svgweb/samples/svg-files/Steps.svg):

> w3 sample

There has to be an issue with the libcinder.org nginx configuration when serving [cinder_logo.svg](https://libcinder.org/docs/_assets/images/cinder_logo.svg).

It's either content-type, security in the headers, or maybe something to do with your ssl certificate.

**Comment by pizthewiz** [comment]
True, it very well could be [CORS](http://www.w3.org/TR/cors/) related as rawgit.com has an explicit:
```
Access-Control-Allow-Origin: *
```

**Comment by jasonsturges** [comment]
I'm starting to think it's your SSL cert, which is missing an intermediate/chain certificate to link to a trusted root certificate.

https://www.sslshopper.com/ssl-checker.html#hostname=https://libcinder.org

You're redirecting all traffic to https, because you're cutting edge and up on standards; however, I wonder if this would just work if you either updated your cert or allowed a http route.

**Comment by jasonsturges** [comment]
I think this has been narrowed down to a SSL issue with libcinder.org.

Even linking to a png such as [expand_arrow.png](https://libcinder.org/docs/_assets/images/expand_arrow.png) via https to libcinder.org fails:
>  

From [atmos/camo](https://github.com/atmos/camo/issues/37#issuecomment-33647214):
> We recently added the behavior to 404 on images where SSL hosts can't be verified.

This is an issue I frequently face with other n-tier architecture, especially on development systems where the certificate chain does not link to a trusted root.  Remote hosts do not trust the connection, ultimately failing in different _4xx_ or _5xx_ status codes.

Presumably you just need to complete your certificate chain by [combining your Comodo SSL certificate](https://support.comodo.com/index.php?/Default/Knowledgebase/Article/View/789/37/certificate-installation-nginx).  As it currently stands, your certificate is not installed correctly.

It would be ideal to address this, for anyone who links to content on your site; or, for certain browsers and crawlers unable to proceed to your site, perhaps without manually trusting to continue.

In the interim, you could use rawgit, or link to a png in the repo.  You could also add github pages such as http://cinder.github.io/cinder/ which I believe could load the SVG.  Basically anything except load the SVG from the repo; or, from libcinder.org.

I'll leave this as is for now; or, advise what you'd like to have done whenever your ready.  Again, not a big deal if you'd prefer to reject this pull request and handle things whenever is convenient for you.

And again, sorry for hassle - untangling web, its caching and proxies is just absolute insanity :scream_cat:

**Comment by andrewfb** [comment]
Thanks for such thorough research on this @pizthewiz and @jasonsturges. We'll try to get this squared away in the next day based on your findings...

**Comment by jasonsturges** [comment]
@andrewfb Looks like you got the certificate resolved - images are now showing up.

**Comment by andrewfb** [comment]
Thanks a lot for your help on tracking this down @jasonsturges - we indeed needed to combine our SSL certs, which Justin Martin took care of.

**Pull request closed without merging**
